version: '3'
services:
  app:
    image: joselfonsecadt/nginx-php7.4-dev:latest
    volumes:
      - ./:/var/www/html
    ports:
      - 80:80
    networks:
      - contable
  horizon:
    image: joselfonsecadt/nginx-php7.4-dev:latest
    command: php /var/www/html/artisan horizon
    volumes:
      - ./:/var/www/html
    networks:
      - contable
  scheduler:
    image: joselfonsecadt/nginx-php7.4-dev:latest
    command: ./var/www/html/bin/run-scheduler.sh
    volumes:
      - ./:/var/www/html
    networks:
      - contable
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: contable
    volumes:
      - ./docker/mysql/data/:/var/lib/mysql
    ports:
      - 3306:3306
    networks:
      - contable
  redis:
    image: redis:5-alpine
    ports:
      - 6379:6379
    networks:
      - contable
networks:
  contable:
    driver: bridge
